security:

    # Permet d'indiquer comment on va récuperer les utilisateurs et leurs authentification
    # Ici on recupere depuis la BDD
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    # La hiérarchie de rôle des utilisateurs
    # ROLE_ADMIN contient les droits de ROLE_SECRETAIRE et de ROLE_USER
    # ROLE_SECRETAIRE contient les droits de ROLE_USER
    role_hierarchy:
        ROLE_ADMIN: [ROLE_SECRETAIRE, ROLE_USER]
        ROLE_SECRETAIRE: [ROLE_USER]


    # Algorithme utilisé pour l'encodage des mots de passe
    encoders:
        App\Entity\User:
            algorithm: auto

    # Permet de definir les composants qui vont permettrent d'identifier l'utilisateur
    # Ils vont écouter sur certaines requêtes et effectuer des opérations particulieres
    firewalls:
        # Aucune authentification pour la partie dev
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: login

    # Permet de définir les niveaux d'accès à notre application
    access_control:
        - { path: /delete, roles: ROLE_ADMIN }
        - { path: /(edit|new)/, roles: ROLE_SECRETAIRE }
